### PR TITLE
Enh simplified list fns

### PR DESCRIPTION
**Pull request by steelec**
to address #1 , implemented functions that rely only on lists of lists rather then expected directory structure.

two functions are added, 
- model_comp_simplified
- compute_average_simplified

I have done internal testing here, looking for external testing @zklsmr and @stremblay18

### CODE REVIEW

**Comment by steelec** [comment]
pinging @zklsmr and @stremblay18 for confirmation that 
1. these two functions work as expected
2. the function comments are accurate
3. the README.md update is accurate

**Comment by zklsmr** [comment]
`model_comp_simplified` runs, and seems to be computing something because it takes 0.7s per subject, but returns a completely empty (0) matrix. 
I couldn't find the source of this problem in the code!

**Comment by zklsmr** [comment]
Also, adding this here as a reminder for when these new functions are done to add them to the import.
https://github.com/neuralabc/mvcomp/issues/3#issue-2177397611

**Comment by steelec** [comment]
> `model_comp_simplified` runs, and seems to be computing something because it takes 0.7s per subject, but returns a completely empty (0) matrix. I couldn't find the source of this problem in the code!

can you include the relevant code that you ran here?

**Comment by steelec** [comment]
just pushed minimal code example for testing, @zklsmr and/or @stremblay18  please try this.

**Comment by zklsmr** [comment]
The notebook works, and I get expected results.
But the globbed paths were missing a `.`, I added it in my last commit! 
thanks!

**Review by zklsmr — APPROVED** [review]

**Pull request merged**
